calibration_complete: false

east:
  turn: right
  inner_radius: 0.05
  outer_radius: 0.14
  p_gain: 1.5

north:
  turn: left
  inner_radius: 0.05
  outer_radius: 0.14
  p_gain: 1.5

west:
  turn: left
  inner_radius: 0.05
  outer_radius: 0.14
  p_gain: 1.5