calibration_complete: true

east:
  turn: right
  turn_speed: 0.4
  turn_bias: 0.25
  reentry_delay_s: 0

north:
  turn: left
  turn_speed: 0.36
  turn_bias: 0.06
  reentry_delay_s: 1.8

west:
  turn: left
  turn_speed: 0.25
  turn_bias: 0.025
  reentry_delay_s: 2.1